package at.ac.univie.hci.btctracker.Activities;

import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.text.Html;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import at.ac.univie.hci.btctracker.Manager.Manager;
import at.ac.univie.hci.btctracker.R;

/**
 * Created by vanish on 10.05.18.
 */

public class WikiActivity extends AppCompatActivity implements AdapterView.OnItemSelectedListener{
    private Manager manager;
    TextView wikiText;
//    String coin;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        manager = new Manager(this);
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_wiki);

        getSupportActionBar().setTitle("Wiki");
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        // creating and setting up coin spinner
        Spinner spinner = (Spinner) findViewById(R.id.wikiSpinner);
        ArrayAdapter<CharSequence> adapter = ArrayAdapter.createFromResource(this,
                R.array.wikiSpin, android.R.layout.simple_spinner_item);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        spinner.setAdapter(adapter);
        spinner.setOnItemSelectedListener(this);
    }

    /**
     * dropdown list of coins
     *
     * @param parent
     * @param view
     * @param pos
     * @param id
     */
    public void onItemSelected(AdapterView<?> parent, View view, int pos, long id) {
        wikiText = findViewById(R.id.wikiText);
        switch (parent.getItemAtPosition(pos).toString()) {
            case "Bitcoin":
                wikiText.setText(Html.fromHtml(btcWiki));
                break;
            case "Ethereum":
                wikiText.setText(Html.fromHtml(ethWiki));
                break;
        }
    }

    /**
     *
     * @param parent
     */
    public void onNothingSelected(AdapterView<?> parent) {
        // show default coin
        wikiText.setText(Html.fromHtml(btcWiki));
    }

    String btcWiki =
            "<b>Info</b> <br> " +
                    "Bitcoin is a cryptocurrency and worldwide payment system." +
                    "It is the first decentralized digital currency, as the system works without a central " +
                    "bank or single administrator.The network is peer-to-peer and transactions " +
                    "take place between users directly, without an intermediary. These transactions " +
                    "are verified by network nodes through the use of cryptography and recorded in a " +
                    "public distributed ledger called a blockchain. Bitcoin was invented by an unknown " +
                    "person or group of people under the name Satoshi Nakamoto and released as " +
                    "open-source software in 2009."
                    + "<br> <br>" +
                    "<b> Speculative bubble dispute </b> <br> " +
                    "Bitcoin has been labelled a speculative bubble by " +
                    "many including former Fed Chairman Alan Greenspan and economist John Quiggin. " +
                    "Nobel Memorial Prize laureate Robert Shiller said that bitcoin \"exhibited many of " +
                    "the characteristics of a speculative bubble\". Journalist Matthew Boesler in 2013 " +
                    "rejected the speculative bubble label and saw bitcoin's quick rise in price as " +
                    "nothing more than normal economic forces at work. Timothy B. Lee, in a 2013 piece " +
                    "for The Washington Post pointed out that the observed cycles of appreciation " +
                    "and depreciation don't correspond to the definition of speculative bubble. " +
                    "On 14 March 2014, the American business magnate Warren Buffett said, \"Stay " +
                    "away from it. It's a mirage, basically.\" During their time as bitcoin " +
                    "developers, Gavin Andresen and Mike Hearn warned that bubbles may occur.";

    String ethWiki  =
            "<b>Info</b> <br> " +
                    "Ethereum is an open-source, public, blockchain-based distributed computing " +
                    "platform and operating system featuring smart contract (scripting) " +
                    "functionality. It supports a modified version of Nakamoto consensus via " +
                    "transaction based state transitions. <br> <br>" +
                    "Ether is a cryptocurrency whose blockchain is generated by the Ethereum " +
                    "platform. Ether can be transferred between accounts and used to compensate " +
                    "participant mining nodes for computations performed. Ethereum provides a " +
                    "decentralized Turing-complete virtual machine, the Ethereum Virtual Machine " +
                    "(EVM), which can execute scripts using an international network of public " +
                    "nodes. \"Gas\", an internal transaction pricing mechanism, is used to " +
                    "mitigate spam and allocate resources on the network.";

    // template for new wiki page
//    String tmp =
//            "<b>Info</b> <br> " +
//                    "" +
//                    "<br> <br>" +
//                    "<b> Speculative bubble dispute </b> <br> " +
//                    "";

    /**
     * Creating a menu
     *
     * @param menu
     * @return
     */

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.main_menu, menu);
        return true;
    }


    /**
     * Open a new Activity on Menu Click
     *
     * @param item
     * @return
     */

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
//            case R.id.transactionMenu:
//                Intent myIntent = new Intent(WikiActivity.this, PortfolioActivity.class);
//                startActivity(myIntent);
//                return true;
            case R.id.home:
                this.finish();
                return true;
            case R.id.wiki:
                Intent wiki = new Intent(WikiActivity.this, WikiActivity.class);
                startActivity(wiki);
                return true;
            case R.id.telegram:
                intentTelegram(this);
                return true;
            case R.id.help:
                startActivity(new Intent(WikiActivity.this, HelpActivity.class));
                return true;
            case R.id.about:
                startActivity(new Intent(WikiActivity.this, PopAboutActivity.class));
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

    /**
     * open telegram channel if it is installed
     *
     * @param context
     */
    void intentTelegram(Context context) {
        Intent i = new Intent(Intent.ACTION_VIEW);
        i.setData(Uri.parse("https://t.me/www_Bitcoin_com"));
        final String appName = "org.telegram.messenger";
        try {
            if (manager.isAppAvailable(this.getApplicationContext(), appName)) {
                i.setPackage(appName);
                this.startActivity(i);
            }
        } catch (Exception e) {
            Toast.makeText(context, "Error. Please read log info", Toast.LENGTH_LONG).show();
        }
    }
}
